'mixed-port': !!int '7890'
'allow-lan': !!bool 'true'
'mode': 'rule'
'log-level': 'info'
'external-controller': '127.0.0.1:9090'
'dns':
  'enable': !!bool 'true'
  'enhanced-mode': 'fake-ip'
  'fake-ip-range': '198.18.0.1/16'
  'nameserver':
  - '8.8.8.8'
  - '1.1.1.1'
'proxies':
- 'name': '🇷🇺 Beget — #2'
  'type': 'vless'
  'server': '193.168.46.180'
  'port': !!int '443'
  'uuid': '5f5e4cfc-0132-4623-a003-87892ba42497'
  'network': 'tcp'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'rruu.persik.host'
  'reality-opts':
    'public-key': 'D0FqzTuVSzCF8IcFo64SFIpMsaGV47LW3el2GCCVoFY'
    'short-id': 'c1a7e9b4711d5f60'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'chrome'
- 'name': '🇷🇺 Beget — #3'
  'type': 'vless'
  'server': '193.168.46.180'
  'port': !!int '443'
  'uuid': '289e4e8b-bf0b-44ff-a06f-1c829c43d5f4'
  'network': 'tcp'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'rruu.persik.host'
  'reality-opts':
    'public-key': 'D0FqzTuVSzCF8IcFo64SFIpMsaGV47LW3el2GCCVoFY'
    'short-id': 'c1a7e9b4711d5f60'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'chrome'
- 'name': '🇷🇺 Beget — #4'
  'type': 'vless'
  'server': '193.168.46.180'
  'port': !!int '443'
  'uuid': '0becfee9-6fb2-46ee-bfa9-4d3d8ea23902'
  'network': 'tcp'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'rruu.persik.host'
  'reality-opts':
    'public-key': 'D0FqzTuVSzCF8IcFo64SFIpMsaGV47LW3el2GCCVoFY'
    'short-id': 'c1a7e9b4711d5f60'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'chrome'
- 'name': '🇷🇺 Beget — #5'
  'type': 'vless'
  'server': '45.12.75.242'
  'port': !!int '26424'
  'uuid': '633f424e-2b11-48da-a6b3-a849dd71456f'
  'network': 'tcp'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'ya.ru'
  'reality-opts':
    'public-key': 'l8AubqcxQO-HRFJy4pZL1vbLOo-eXit69s-XulSELE0'
    'short-id': '23103e1e'
  'client-fingerprint': 'chrome'
- 'name': '🇷🇺 Beget — #6'
  'type': 'vless'
  'server': '45.12.75.242'
  'port': !!int '26424'
  'uuid': '633f424e-2b11-48da-a6b3-a849dd71456f'
  'network': 'tcp'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'ya.ru'
  'reality-opts':
    'public-key': 'l8AubqcxQO-HRFJy4pZL1vbLOo-eXit69s-XulSELE0'
    'short-id': '23103e1e'
  'client-fingerprint': 'chrome'
- 'name': '🇷🇺 UFO Hosting — #7'
  'type': 'vless'
  'server': '45.67.230.230'
  'port': !!int '443'
  'uuid': '20ecee51-1044-4be3-89a9-f3c700425ead'
  'network': 'tcp'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'yahoo.com'
  'reality-opts':
    'public-key': 'qYg2nPdLpBYWM7-9leTq43SoqAc5nT90gFH-AHAMShY'
    'short-id': 'abb1'
  'client-fingerprint': 'chrome'
- 'name': '🇷🇺 UFO Hosting — #8'
  'type': 'vless'
  'server': '45.67.230.230'
  'port': !!int '443'
  'uuid': '20ecee51-1044-4be3-89a9-f3c700425ead'
  'network': 'tcp'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'yahoo.com'
  'reality-opts':
    'public-key': 'qYg2nPdLpBYWM7-9leTq43SoqAc5nT90gFH-AHAMShY'
    'short-id': 'abb1'
  'client-fingerprint': 'chrome'
- 'name': '🇨🇿 Czechia — #9'
  'type': 'vless'
  'server': '158.160.249.158'
  'port': !!int '8443'
  'uuid': 'f9a43aa2-0599-4f16-b40c-b47952ffc78a'
  'network': 'tcp'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'ads.x5.ru'
  'reality-opts':
    'public-key': 'r5WB5FnSCt4eeBC1FJMfkWHbzsMuabo0Rc6wuAhlZUs'
    'short-id': '71f0b07a98c840c7'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'chrome'
- 'name': '🇨🇿 Czechia — #10'
  'type': 'vless'
  'server': '5.188.114.12'
  'port': !!int '7443'
  'uuid': '81bc17b1-f73d-419c-a50b-9e2a4d255dfb'
  'network': 'grpc'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': '5post-gate.x5.ru'
  'reality-opts':
    'public-key': 'ERpf2EHDDsmDMRSSl8FWBUqopf3RkAd_2W7n7qcM5z8'
    'short-id': 'f0a022c75e76'
  'client-fingerprint': 'chrome'
- 'name': '🇫🇮 Finland — #11'
  'type': 'vless'
  'server': '5.42.100.213'
  'port': !!int '8443'
  'uuid': 'bdddc783-a4f3-47f7-8850-21416d0a31f1'
  'network': 'tcp'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'sun6-21.userapi.com'
  'reality-opts':
    'public-key': 'Zr37gJWVIvP9JsYN3cqySyvpo2SoOcZClA5e-qHsPCE'
    'short-id': 'cfb415a429e83b04'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'chrome'
- 'name': '🇲🇩 Moldova — #12'
  'type': 'vless'
  'server': '185.242.19.251'
  'port': !!int '443'
  'uuid': 'cfb70000-ed61-4a7e-89a3-2b9c2caa6001'
  'network': 'ws'
  'udp': !!bool 'true'
- 'name': '🇳🇱 The Netherlands — #13'
  'type': 'vless'
  'server': '178.154.194.99'
  'port': !!int '443'
  'uuid': '4f4f9461-5cfa-4746-9f62-2f08dfd05636'
  'network': 'tcp'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'pornhub.com'
  'reality-opts':
    'public-key': 'YJ9I6GzZ_xT_Rk8We8iR1CwEMbzF4I30i_EH2VOVY0Y'
    'short-id': 'abab34c40ed6c10a'
  'client-fingerprint': 'chrome'
- 'name': '🇳🇱 The Netherlands — #14'
  'type': 'vless'
  'server': '178.154.194.68'
  'port': !!int '443'
  'uuid': '4f4f9461-5cfa-4746-9f62-2f08dfd05636'
  'network': 'tcp'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'pornhub.com'
  'reality-opts':
    'public-key': 'YJ9I6GzZ_xT_Rk8We8iR1CwEMbzF4I30i_EH2VOVY0Y'
    'short-id': 'abab34c40ed6c10a'
  'client-fingerprint': 'chrome'
- 'name': '🇺🇸 United States — #15'
  'type': 'vless'
  'server': '212.233.99.62'
  'port': !!int '443'
  'uuid': '7be400d9-67ad-4819-bd06-c889308f12d0'
  'network': 'xhttp'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'vk.com'
  'reality-opts':
    'public-key': 'iIhrPpoPQN1gDf8coQ8o54-oTRdYFpLD7I7e9tHF0EE'
    'short-id': 'a977328085692dc8'
  'client-fingerprint': 'chrome'
- 'name': '🇺🇸 United States — #16'
  'type': 'vless'
  'server': '155.212.146.195'
  'port': !!int '443'
  'uuid': '91a3f712-c4e0-42a0-9475-bdd551a06e73'
  'network': 'xhttp'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'ads.x5.ru'
  'reality-opts':
    'public-key': 'AhQkw1Ydp_ZkXnE7UbIZvwHk9KE_Bf5_TkojYZZUuGs'
    'short-id': '2da46294d6a521B2'
  'client-fingerprint': 'chrome'
'proxy-groups':
- 'name': 'PROXY'
  'type': 'select'
  'proxies':
  - '🚀 Авто'
  - '📺 YouTube'
  - '🎮 League'
  - '🇩🇪 Frankfurt'
  - '🇵🇱 Polska'
  - '🇪🇪 Eesti'
  - '🇭🇺 Hungary'
  - '⚡ Российские'
  - '🇷🇺 Beget — #2'
  - '🇷🇺 Beget — #3'
  - '🇷🇺 Beget — #4'
  - '🇷🇺 Beget — #5'
  - '🇷🇺 Beget — #6'
  - '🇷🇺 UFO Hosting — #7'
  - '🇷🇺 UFO Hosting — #8'
  - '🇨🇿 Czechia — #9'
  - '🇨🇿 Czechia — #10'
  - '🇫🇮 Finland — #11'
  - '🇲🇩 Moldova — #12'
  - '🇳🇱 The Netherlands — #13'
  - '🇳🇱 The Netherlands — #14'
  - '🇺🇸 United States — #15'
  - '🇺🇸 United States — #16'
- 'name': '🚀 Авто'
  'type': 'url-test'
  'proxies':
  - '🇷🇺 Beget — #2'
  - '🇷🇺 Beget — #3'
  - '🇷🇺 Beget — #4'
  - '🇷🇺 Beget — #5'
  - '🇷🇺 Beget — #6'
  - '🇷🇺 UFO Hosting — #7'
  - '🇷🇺 UFO Hosting — #8'
  - '🇨🇿 Czechia — #9'
  - '🇨🇿 Czechia — #10'
  - '🇫🇮 Finland — #11'
  - '🇲🇩 Moldova — #12'
  - '🇳🇱 The Netherlands — #13'
  - '🇳🇱 The Netherlands — #14'
  - '🇺🇸 United States — #15'
  - '🇺🇸 United States — #16'
  'url': 'https://www.google.com/generate_204'
  'interval': !!int '60'
  'tolerance': !!int '100'
- 'name': '📺 YouTube'
  'type': 'url-test'
  'proxies':
  - '🇨🇿 Czechia — #9'
  - '🇨🇿 Czechia — #10'
  - '🇫🇮 Finland — #11'
  - '🇲🇩 Moldova — #12'
  - '🇳🇱 The Netherlands — #13'
  - '🇳🇱 The Netherlands — #14'
  - '🇺🇸 United States — #15'
  - '🇺🇸 United States — #16'
  'url': 'https://www.youtube.com/generate_204'
  'interval': !!int '120'
  'tolerance': !!int '150'
- 'name': '🎮 League'
  'type': 'url-test'
  'proxies': &id001
  - '🇷🇺 Beget — #2'
  - '🇷🇺 Beget — #3'
  - '🇷🇺 Beget — #4'
  - '🇷🇺 Beget — #5'
  - '🇷🇺 Beget — #6'
  - '🇷🇺 UFO Hosting — #7'
  - '🇷🇺 UFO Hosting — #8'
  'url': 'https://www.google.com/generate_204'
  'interval': !!int '60'
  'tolerance': !!int '30'
- 'name': '🇩🇪 Frankfurt'
  'type': 'url-test'
  'proxies':
  - '🇨🇿 Czechia — #9'
  - '🇨🇿 Czechia — #10'
  - '🇫🇮 Finland — #11'
  - '🇲🇩 Moldova — #12'
  - '🇳🇱 The Netherlands — #13'
  - '🇳🇱 The Netherlands — #14'
  - '🇺🇸 United States — #15'
  - '🇺🇸 United States — #16'
  'url': 'https://cloudflare.com/cdn-cgi/trace'
  'interval': !!int '60'
  'tolerance': !!int '50'
- 'name': '🇵🇱 Polska'
  'type': 'url-test'
  'proxies':
  - '🇨🇿 Czechia — #9'
  - '🇨🇿 Czechia — #10'
  - '🇫🇮 Finland — #11'
  - '🇲🇩 Moldova — #12'
  - '🇳🇱 The Netherlands — #13'
  - '🇳🇱 The Netherlands — #14'
  - '🇺🇸 United States — #15'
  - '🇺🇸 United States — #16'
  'url': 'https://cloudflare.com/cdn-cgi/trace'
  'interval': !!int '60'
  'tolerance': !!int '50'
- 'name': '🇪🇪 Eesti'
  'type': 'url-test'
  'proxies':
  - '🇨🇿 Czechia — #9'
  - '🇨🇿 Czechia — #10'
  - '🇫🇮 Finland — #11'
  - '🇲🇩 Moldova — #12'
  - '🇳🇱 The Netherlands — #13'
  - '🇳🇱 The Netherlands — #14'
  - '🇺🇸 United States — #15'
  - '🇺🇸 United States — #16'
  'url': 'https://cloudflare.com/cdn-cgi/trace'
  'interval': !!int '60'
  'tolerance': !!int '50'
- 'name': '🇭🇺 Hungary'
  'type': 'url-test'
  'proxies':
  - '🇨🇿 Czechia — #9'
  - '🇨🇿 Czechia — #10'
  - '🇫🇮 Finland — #11'
  - '🇲🇩 Moldova — #12'
  - '🇳🇱 The Netherlands — #13'
  - '🇳🇱 The Netherlands — #14'
  - '🇺🇸 United States — #15'
  - '🇺🇸 United States — #16'
  'url': 'https://cloudflare.com/cdn-cgi/trace'
  'interval': !!int '60'
  'tolerance': !!int '50'
- 'name': '⚡ Российские'
  'type': 'url-test'
  'proxies': *id001
  'url': 'https://yandex.ru/internet'
  'interval': !!int '60'
  'tolerance': !!int '30'
'rules':
- 'DOMAIN-SUFFIX,youtube.com,📺 YouTube'
- 'DOMAIN-SUFFIX,googlevideo.com,📺 YouTube'
- 'DOMAIN-SUFFIX,ytimg.com,📺 YouTube'
- 'DOMAIN-SUFFIX,ggpht.com,📺 YouTube'
- 'DOMAIN-SUFFIX,youtu.be,📺 YouTube'
- 'DOMAIN,youtube.googleapis.com,📺 YouTube'
- 'DOMAIN-SUFFIX,twitch.tv,📺 YouTube'
- 'DOMAIN-SUFFIX,netflix.com,📺 YouTube'
- 'DOMAIN-SUFFIX,hulu.com,📺 YouTube'
- 'MATCH,PROXY'
