'mixed-port': !!int '7890'
'allow-lan': !!bool 'true'
'mode': 'rule'
'log-level': 'info'
'external-controller': '127.0.0.1:9090'
'dns':
  'enable': !!bool 'true'
  'enhanced-mode': 'fake-ip'
  'fake-ip-range': '198.18.0.1/16'
  'nameserver':
  - '8.8.8.8'
  - '1.1.1.1'
'proxies':
- 'name': '🇷🇺 Beget — #1'
  'type': 'vless'
  'server': '45.12.75.242'
  'port': !!int '26424'
  'uuid': '633f424e-2b11-48da-a6b3-a849dd71456f'
  'network': 'tcp'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'ya.ru'
  'reality-opts':
    'public-key': 'l8AubqcxQO-HRFJy4pZL1vbLOo-eXit69s-XulSELE0'
    'short-id': '23103e1e'
  'client-fingerprint': 'randomized'
- 'name': '🇷🇺 Beget — #2'
  'type': 'vless'
  'server': '193.168.46.180'
  'port': !!int '443'
  'uuid': '1d8a2cb9-4910-4bdb-8e06-28ce42d51608'
  'network': 'tcp'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'rruu.persik.host'
  'reality-opts':
    'public-key': 'D0FqzTuVSzCF8IcFo64SFIpMsaGV47LW3el2GCCVoFY'
    'short-id': 'c1a7e9b4711d5f60'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'chrome'
- 'name': '🇷🇺 Beget — #3'
  'type': 'vless'
  'server': '193.168.46.180'
  'port': !!int '443'
  'uuid': '099e940c-722f-4812-a270-8c254fe046c2'
  'network': 'tcp'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'rruu.persik.host'
  'reality-opts':
    'public-key': 'D0FqzTuVSzCF8IcFo64SFIpMsaGV47LW3el2GCCVoFY'
    'short-id': 'c1a7e9b4711d5f60'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'chrome'
- 'name': '🇷🇺 Beget — #4'
  'type': 'vless'
  'server': '193.168.46.180'
  'port': !!int '443'
  'uuid': '099e940c-722f-4812-a270-8c254fe046c2'
  'network': 'tcp'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'rruu.persik.host'
  'reality-opts':
    'public-key': 'D0FqzTuVSzCF8IcFo64SFIpMsaGV47LW3el2GCCVoFY'
    'short-id': 'c1a7e9b4711d5f60'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'chrome'
- 'name': '🇷🇺 Beget — #5'
  'type': 'vless'
  'server': '193.168.46.180'
  'port': !!int '443'
  'uuid': '0becfee9-6fb2-46ee-bfa9-4d3d8ea23902'
  'network': 'tcp'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'rruu.persik.host'
  'reality-opts':
    'public-key': 'D0FqzTuVSzCF8IcFo64SFIpMsaGV47LW3el2GCCVoFY'
    'short-id': 'c1a7e9b4711d5f60'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'chrome'
- 'name': '🇷🇺 Beget — #6'
  'type': 'vless'
  'server': '193.168.46.180'
  'port': !!int '443'
  'uuid': '3dd0c73a-7e7e-4ada-a4df-c33a8c25ca53'
  'network': 'tcp'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'rruu.persik.host'
  'reality-opts':
    'public-key': 'D0FqzTuVSzCF8IcFo64SFIpMsaGV47LW3el2GCCVoFY'
    'short-id': 'c1a7e9b4711d5f60'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'chrome'
- 'name': '🇷🇺 Beget — #7'
  'type': 'vless'
  'server': '193.168.46.180'
  'port': !!int '443'
  'uuid': 'bfb5a2a2-aa43-4387-ad0b-b6c647119aed'
  'network': 'tcp'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'rruu.persik.host'
  'reality-opts':
    'public-key': 'D0FqzTuVSzCF8IcFo64SFIpMsaGV47LW3el2GCCVoFY'
    'short-id': 'c1a7e9b4711d5f60'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'chrome'
- 'name': '🇷🇺 Beget — #8'
  'type': 'vless'
  'server': '45.12.75.242'
  'port': !!int '26424'
  'uuid': '633f424e-2b11-48da-a6b3-a849dd71456f'
  'network': 'tcp'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'ya.ru'
  'reality-opts':
    'public-key': 'l8AubqcxQO-HRFJy4pZL1vbLOo-eXit69s-XulSELE0'
    'short-id': '23103e1e'
  'client-fingerprint': 'chrome'
- 'name': '🇷🇺 Beget — #9'
  'type': 'vless'
  'server': '45.12.75.242'
  'port': !!int '26424'
  'uuid': '633f424e-2b11-48da-a6b3-a849dd71456f'
  'network': 'tcp'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'ya.ru'
  'reality-opts':
    'public-key': 'l8AubqcxQO-HRFJy4pZL1vbLOo-eXit69s-XulSELE0'
    'short-id': '23103e1e'
  'client-fingerprint': 'chrome'
- 'name': '🇷🇺 GIR SER — #10'
  'type': 'vless'
  'server': '51.250.113.157'
  'port': !!int '443'
  'uuid': 'b6083a84-80a5-3e88-9dbb-5c8ef241be3a'
  'network': 'tcp'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'www.google.com'
  'reality-opts':
    'public-key': '65nqcY-jE1J_G27W-X_qGCSpXMEHif6MBLXN8kBoFB0'
    'short-id': '1f18adc24d1d'
  'client-fingerprint': 'random'
- 'name': '🇷🇺 Timeweb — #11'
  'type': 'vless'
  'server': '185.242.19.252'
  'port': !!int '443'
  'uuid': 'dbb9c679-7f0f-4649-97aa-342d77796c69'
  'network': 'xhttp'
  'udp': !!bool 'true'
- 'name': '🇷🇺 UFO Hosting — #12'
  'type': 'vless'
  'server': '45.67.230.230'
  'port': !!int '443'
  'uuid': '20ecee51-1044-4be3-89a9-f3c700425ead'
  'network': 'tcp'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'yahoo.com'
  'reality-opts':
    'public-key': 'qYg2nPdLpBYWM7-9leTq43SoqAc5nT90gFH-AHAMShY'
    'short-id': 'abb1'
  'client-fingerprint': 'chrome'
- 'name': '🇷🇺 UFO Hosting — #13'
  'type': 'vless'
  'server': '45.67.230.230'
  'port': !!int '443'
  'uuid': '20ecee51-1044-4be3-89a9-f3c700425ead'
  'network': 'tcp'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'yahoo.com'
  'reality-opts':
    'public-key': 'qYg2nPdLpBYWM7-9leTq43SoqAc5nT90gFH-AHAMShY'
    'short-id': 'abb1'
  'client-fingerprint': 'chrome'
- 'name': '🇩🇪 Germany — #14'
  'type': 'vless'
  'server': '111.88.145.222'
  'port': !!int '8443'
  'uuid': '17564323-6830-4ea0-a9d3-4d25ec55e7b6'
  'network': 'tcp'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'max.ru'
  'reality-opts':
    'public-key': 'ISa-DZOI4LRRb9DHMFYm5oFqBXDjYzz0hVWUfWvzLmo'
    'short-id': '8d3293f0066e129a'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'firefox'
- 'name': '🇫🇮 Finland — #15'
  'type': 'vless'
  'server': '158.160.199.1'
  'port': !!int '6443'
  'uuid': '196896b8-29cd-4437-b4f7-dad1a29f1ef8'
  'network': 'tcp'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'apiok.ru'
  'reality-opts':
    'public-key': 'vnT4OJUgZ1YdGBSyzXN6EWctKLH0qtqA81OMgOvNqT4'
    'short-id': 'ad7dab264a323acb'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'randomized'
- 'name': '🇫🇮 Finland — #16'
  'type': 'vless'
  'server': '158.160.199.1'
  'port': !!int '6443'
  'uuid': '196896b8-29cd-4437-b4f7-dad1a29f1ef8'
  'network': 'tcp'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'apiok.ru'
  'reality-opts':
    'public-key': 'vnT4OJUgZ1YdGBSyzXN6EWctKLH0qtqA81OMgOvNqT4'
    'short-id': 'ad7dab264a323acb'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'qq'
- 'name': '🇫🇮 Finland — #17'
  'type': 'vless'
  'server': '158.160.199.1'
  'port': !!int '6443'
  'uuid': '196896b8-29cd-4437-b4f7-dad1a29f1ef8'
  'network': 'tcp'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'apiok.ru'
  'reality-opts':
    'public-key': 'vnT4OJUgZ1YdGBSyzXN6EWctKLH0qtqA81OMgOvNqT4'
    'short-id': 'ad7dab264a323acb'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'qq'
- 'name': '🇲🇩 Moldova — #18'
  'type': 'vless'
  'server': '185.242.19.252'
  'port': !!int '443'
  'uuid': 'cfb70000-ed61-4a7e-89a3-2b9c2caa6001'
  'network': 'ws'
  'udp': !!bool 'true'
'proxy-groups':
- 'name': 'PROXY'
  'type': 'select'
  'proxies':
  - '🚀 Авто'
  - '📺 YouTube'
  - '🎮 League'
  - '🇩🇪 Frankfurt'
  - '🇵🇱 Polska'
  - '🇪🇪 Eesti'
  - '🇭🇺 Hungary'
  - '⚡ Российские'
  - '🇷🇺 Beget — #1'
  - '🇷🇺 Beget — #2'
  - '🇷🇺 Beget — #3'
  - '🇷🇺 Beget — #4'
  - '🇷🇺 Beget — #5'
  - '🇷🇺 Beget — #6'
  - '🇷🇺 Beget — #7'
  - '🇷🇺 Beget — #8'
  - '🇷🇺 Beget — #9'
  - '🇷🇺 GIR SER — #10'
  - '🇷🇺 Timeweb — #11'
  - '🇷🇺 UFO Hosting — #12'
  - '🇷🇺 UFO Hosting — #13'
  - '🇩🇪 Germany — #14'
  - '🇫🇮 Finland — #15'
  - '🇫🇮 Finland — #16'
  - '🇫🇮 Finland — #17'
  - '🇲🇩 Moldova — #18'
- 'name': '🚀 Авто'
  'type': 'url-test'
  'proxies':
  - '🇷🇺 Beget — #1'
  - '🇷🇺 Beget — #2'
  - '🇷🇺 Beget — #3'
  - '🇷🇺 Beget — #4'
  - '🇷🇺 Beget — #5'
  - '🇷🇺 Beget — #6'
  - '🇷🇺 Beget — #7'
  - '🇷🇺 Beget — #8'
  - '🇷🇺 Beget — #9'
  - '🇷🇺 GIR SER — #10'
  - '🇷🇺 Timeweb — #11'
  - '🇷🇺 UFO Hosting — #12'
  - '🇷🇺 UFO Hosting — #13'
  - '🇩🇪 Germany — #14'
  - '🇫🇮 Finland — #15'
  - '🇫🇮 Finland — #16'
  - '🇫🇮 Finland — #17'
  - '🇲🇩 Moldova — #18'
  'url': 'https://www.google.com/generate_204'
  'interval': !!int '60'
  'tolerance': !!int '100'
- 'name': '📺 YouTube'
  'type': 'url-test'
  'proxies':
  - '🇩🇪 Germany — #14'
  - '🇫🇮 Finland — #15'
  - '🇫🇮 Finland — #16'
  - '🇫🇮 Finland — #17'
  - '🇲🇩 Moldova — #18'
  'url': 'https://www.youtube.com/generate_204'
  'interval': !!int '120'
  'tolerance': !!int '150'
- 'name': '🎮 League'
  'type': 'url-test'
  'proxies': &id001
  - '🇷🇺 Beget — #1'
  - '🇷🇺 Beget — #2'
  - '🇷🇺 Beget — #3'
  - '🇷🇺 Beget — #4'
  - '🇷🇺 Beget — #5'
  - '🇷🇺 Beget — #6'
  - '🇷🇺 Beget — #7'
  - '🇷🇺 Beget — #8'
  - '🇷🇺 Beget — #9'
  - '🇷🇺 GIR SER — #10'
  - '🇷🇺 Timeweb — #11'
  - '🇷🇺 UFO Hosting — #12'
  - '🇷🇺 UFO Hosting — #13'
  'url': 'https://www.google.com/generate_204'
  'interval': !!int '60'
  'tolerance': !!int '30'
- 'name': '🇩🇪 Frankfurt'
  'type': 'url-test'
  'proxies':
  - '🇩🇪 Germany — #14'
  'url': 'https://cloudflare.com/cdn-cgi/trace'
  'interval': !!int '60'
  'tolerance': !!int '50'
- 'name': '🇵🇱 Polska'
  'type': 'url-test'
  'proxies':
  - '🇩🇪 Germany — #14'
  - '🇫🇮 Finland — #15'
  - '🇫🇮 Finland — #16'
  - '🇫🇮 Finland — #17'
  - '🇲🇩 Moldova — #18'
  'url': 'https://cloudflare.com/cdn-cgi/trace'
  'interval': !!int '60'
  'tolerance': !!int '50'
- 'name': '🇪🇪 Eesti'
  'type': 'url-test'
  'proxies':
  - '🇩🇪 Germany — #14'
  - '🇫🇮 Finland — #15'
  - '🇫🇮 Finland — #16'
  - '🇫🇮 Finland — #17'
  - '🇲🇩 Moldova — #18'
  'url': 'https://cloudflare.com/cdn-cgi/trace'
  'interval': !!int '60'
  'tolerance': !!int '50'
- 'name': '🇭🇺 Hungary'
  'type': 'url-test'
  'proxies':
  - '🇩🇪 Germany — #14'
  - '🇫🇮 Finland — #15'
  - '🇫🇮 Finland — #16'
  - '🇫🇮 Finland — #17'
  - '🇲🇩 Moldova — #18'
  'url': 'https://cloudflare.com/cdn-cgi/trace'
  'interval': !!int '60'
  'tolerance': !!int '50'
- 'name': '⚡ Российские'
  'type': 'url-test'
  'proxies': *id001
  'url': 'https://yandex.ru/internet'
  'interval': !!int '60'
  'tolerance': !!int '30'
'rules':
- 'DOMAIN-SUFFIX,youtube.com,📺 YouTube'
- 'DOMAIN-SUFFIX,googlevideo.com,📺 YouTube'
- 'DOMAIN-SUFFIX,ytimg.com,📺 YouTube'
- 'DOMAIN-SUFFIX,ggpht.com,📺 YouTube'
- 'DOMAIN-SUFFIX,youtu.be,📺 YouTube'
- 'DOMAIN,youtube.googleapis.com,📺 YouTube'
- 'DOMAIN-SUFFIX,twitch.tv,📺 YouTube'
- 'DOMAIN-SUFFIX,netflix.com,📺 YouTube'
- 'DOMAIN-SUFFIX,hulu.com,📺 YouTube'
- 'MATCH,PROXY'
