'mixed-port': !!int '7890'
'allow-lan': !!bool 'true'
'mode': 'rule'
'log-level': 'info'
'external-controller': '127.0.0.1:9090'
'dns':
  'enable': !!bool 'true'
  'enhanced-mode': 'fake-ip'
  'fake-ip-range': '198.18.0.1/16'
  'nameserver':
  - '8.8.8.8'
  - '1.1.1.1'
'proxies':
- 'name': '⚠️ Lite-версия подписки устарела'
  'type': 'vless'
  'server': '0.0.0.0'
  'port': !!int '1'
  'uuid': '00000000-0000-0000-0000-000000000000'
  'network': 'tcp'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'zieng2.org'
  'reality-opts':
    'public-key': 'dE3wtv44FXcZGAp0MYiYYa79zxJlcVNmPN5t8qa0cTs'
    'short-id': '7a69656e6732'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'chrome'
- 'name': 'Обновите ссылку на актуальную'
  'type': 'vless'
  'server': '0.0.0.0'
  'port': !!int '2'
  'uuid': '00000000-0000-0000-0000-000000000000'
  'network': 'tcp'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'zieng2.org'
  'reality-opts':
    'public-key': '2nubdAYgPRiVoB88RsXViyhp9TchqXY6WmQtFELv4nA'
    'short-id': '7a69656e6733'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'chrome'
- 'name': 'https://github.com/zieng2/wl'
  'type': 'vless'
  'server': '0.0.0.0'
  'port': !!int '3'
  'uuid': '00000000-0000-0000-0000-000000000000'
  'network': 'tcp'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'zieng2.org'
  'reality-opts':
    'public-key': 'ssvmqwroFTDVi1v2Jkmqlo8QoArjaLyJ17lq6BhIlzo'
    'short-id': '7a69656e6734'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'chrome'
- 'name': 'https://t.me/zieng2'
  'type': 'vless'
  'server': '0.0.0.0'
  'port': !!int '4'
  'uuid': '00000000-0000-0000-0000-000000000000'
  'network': 'tcp'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'zieng2.org'
  'reality-opts':
    'public-key': 'ACX4SiuP3kQfZmK6VIirXhBhgafl3CEjLZGITY2MGVg'
    'short-id': '7a69656e6735'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'chrome'
- 'name': '🇷🇺 Beget — #1'
  'type': 'vless'
  'server': '45.12.75.242'
  'port': !!int '26424'
  'uuid': '633f424e-2b11-48da-a6b3-a849dd71456f'
  'network': 'raw'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'ya.ru'
  'reality-opts':
    'public-key': 'l8AubqcxQO-HRFJy4pZL1vbLOo-eXit69s-XulSELE0'
    'short-id': '23103e1e'
  'client-fingerprint': 'chrome'
- 'name': '🇷🇺 Beget — #2'
  'type': 'vless'
  'server': '45.12.75.242'
  'port': !!int '26424'
  'uuid': '633f424e-2b11-48da-a6b3-a849dd71456f'
  'network': 'raw'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'ya.ru'
  'reality-opts':
    'public-key': 'l8AubqcxQO-HRFJy4pZL1vbLOo-eXit69s-XulSELE0'
    'short-id': '23103e1e'
  'client-fingerprint': 'qq'
- 'name': '🇷🇺 Beget — #3'
  'type': 'vless'
  'server': '45.12.75.242'
  'port': !!int '26424'
  'uuid': '633f424e-2b11-48da-a6b3-a849dd71456f'
  'network': 'raw'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'ya.ru'
  'reality-opts':
    'public-key': 'l8AubqcxQO-HRFJy4pZL1vbLOo-eXit69s-XulSELE0'
    'short-id': '23103e1e'
  'client-fingerprint': 'chrome'
- 'name': '🇷🇺 Beget — #4'
  'type': 'vless'
  'server': '45.12.75.242'
  'port': !!int '26424'
  'uuid': '633f424e-2b11-48da-a6b3-a849dd71456f'
  'network': 'raw'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'ya.ru'
  'reality-opts':
    'public-key': 'l8AubqcxQO-HRFJy4pZL1vbLOo-eXit69s-XulSELE0'
    'short-id': '23103e1e'
  'client-fingerprint': 'firefox'
- 'name': '🇷🇺 MegaMax Network — #5'
  'type': 'vless'
  'server': '212.67.9.113'
  'port': !!int '2200'
  'uuid': '2aa7f4b1-e859-46d0-b8ac-8587811ab7b1'
  'network': 'ws'
  'udp': !!bool 'true'
- 'name': '🇦🇹 Austria — #6'
  'type': 'vless'
  'server': '188.68.218.205'
  'port': !!int '443'
  'uuid': '6aaa7d1d-8b35-4fd2-ae60-0129ad624935'
  'network': 'grpc'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'static-basket-01.wbbasket.ru'
  'reality-opts':
    'public-key': '8dPBbufX7ST4NrD8Etatp_FR_mbd38vXa2ZXCVLxjQ4'
    'short-id': '0fc62d3cd3089adb'
  'client-fingerprint': 'safari'
- 'name': '🇦🇹 Austria — #7'
  'type': 'vless'
  'server': '188.68.218.205'
  'port': !!int '443'
  'uuid': '6aaa7d1d-8b35-4fd2-ae60-0129ad624935'
  'network': 'grpc'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'static-basket-01.wbbasket.ru'
  'reality-opts':
    'public-key': '8dPBbufX7ST4NrD8Etatp_FR_mbd38vXa2ZXCVLxjQ4'
    'short-id': '0fc62d3cd3089adb'
  'client-fingerprint': 'edge'
- 'name': '🇦🇹 Austria — #8'
  'type': 'vless'
  'server': '188.68.218.205'
  'port': !!int '443'
  'uuid': '6aaa7d1d-8b35-4fd2-ae60-0129ad624935'
  'network': 'grpc'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'static-basket-01.wbbasket.ru'
  'reality-opts':
    'public-key': '8dPBbufX7ST4NrD8Etatp_FR_mbd38vXa2ZXCVLxjQ4'
    'short-id': '0fc62d3cd3089adb'
  'client-fingerprint': 'firefox'
- 'name': '🇦🇹 Austria — #9'
  'type': 'vless'
  'server': '188.68.218.205'
  'port': !!int '443'
  'uuid': '6aaa7d1d-8b35-4fd2-ae60-0129ad624935'
  'network': 'grpc'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'static-basket-01.wbbasket.ru'
  'reality-opts':
    'public-key': '8dPBbufX7ST4NrD8Etatp_FR_mbd38vXa2ZXCVLxjQ4'
    'short-id': '0fc62d3cd3089adb'
  'client-fingerprint': 'chrome'
- 'name': '🇦🇹 Austria — #10'
  'type': 'vless'
  'server': '188.68.218.205'
  'port': !!int '443'
  'uuid': '6aaa7d1d-8b35-4fd2-ae60-0129ad624935'
  'network': 'grpc'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'static-basket-01.wbbasket.ru'
  'reality-opts':
    'public-key': '8dPBbufX7ST4NrD8Etatp_FR_mbd38vXa2ZXCVLxjQ4'
    'short-id': '0fc62d3cd3089adb'
  'client-fingerprint': 'qq'
- 'name': '🇦🇹 Austria — #11'
  'type': 'vless'
  'server': '188.68.218.205'
  'port': !!int '443'
  'uuid': '6aaa7d1d-8b35-4fd2-ae60-0129ad624935'
  'network': 'grpc'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'static-basket-01.wbbasket.ru'
  'reality-opts':
    'public-key': '8dPBbufX7ST4NrD8Etatp_FR_mbd38vXa2ZXCVLxjQ4'
    'short-id': '0fc62d3cd3089adb'
  'client-fingerprint': 'ios'
- 'name': '🇨🇭 Switzerland — #12'
  'type': 'vless'
  'server': '188.68.216.38'
  'port': !!int '9882'
  'uuid': '5d16ac22-6eea-426f-b778-6f4c2961faef'
  'network': 'grpc'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'dl.google.com'
  'reality-opts':
    'public-key': 'bnRIb3Er1i-K6NGGByCO9UbGfOvu43ZoiK7ulPd1SzU'
    'short-id': 'aa'
  'client-fingerprint': 'qq'
- 'name': '🇨🇿 Czechia — #13'
  'type': 'vless'
  'server': '78.159.247.205'
  'port': !!int '443'
  'uuid': '92089155-6602-4122-86d4-fe6de20e8c4d'
  'network': 'raw'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'kinopoisk.ru'
  'reality-opts':
    'public-key': 'NsTRRl4ofT64w0VwmkpOWE8yfiXLcEqgwgi-9SGnXTA'
    'short-id': 'a1b2c3d4'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'firefox'
- 'name': '🇨🇿 Czechia — #14'
  'type': 'vless'
  'server': '78.159.247.170'
  'port': !!int '443'
  'uuid': '92089155-6602-4122-86d4-fe6de20e8c4d'
  'network': 'raw'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'kinopoisk.ru'
  'reality-opts':
    'public-key': 'NsTRRl4ofT64w0VwmkpOWE8yfiXLcEqgwgi-9SGnXTA'
    'short-id': 'a1b2c3d4'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'firefox'
- 'name': '🇨🇿 Czechia — #15'
  'type': 'vless'
  'server': '78.159.247.214'
  'port': !!int '443'
  'uuid': '92089155-6602-4122-86d4-fe6de20e8c4d'
  'network': 'raw'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'kinopoisk.ru'
  'reality-opts':
    'public-key': 'NsTRRl4ofT64w0VwmkpOWE8yfiXLcEqgwgi-9SGnXTA'
    'short-id': 'a1b2c3d4'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'firefox'
- 'name': '🇩🇪 Germany — #16'
  'type': 'vless'
  'server': '188.68.216.38'
  'port': !!int '9891'
  'uuid': '5d16ac22-6eea-426f-b778-6f4c2961faef'
  'network': 'grpc'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'dl.google.com'
  'reality-opts':
    'public-key': 'Dfgu8Ey0M8Hz4gXGZAwQ3H9jLt2HByVsjAOTWiuKDB0'
    'short-id': 'aabbccdd'
  'client-fingerprint': 'firefox'
- 'name': '🇩🇪 Germany — #17'
  'type': 'vless'
  'server': '188.68.216.38'
  'port': !!int '9891'
  'uuid': '5d16ac22-6eea-426f-b778-6f4c2961faef'
  'network': 'grpc'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'dl.google.com'
  'reality-opts':
    'public-key': 'Dfgu8Ey0M8Hz4gXGZAwQ3H9jLt2HByVsjAOTWiuKDB0'
    'short-id': 'aabbccdd'
  'client-fingerprint': 'qq'
- 'name': '🇳🇱 The Netherlands — #19'
  'type': 'vless'
  'server': '95.163.232.171'
  'port': !!int '14443'
  'uuid': 'fb67fd37-8d41-43a9-a093-c0b807fc5299'
  'network': 'ws'
  'udp': !!bool 'true'
- 'name': '🇳🇱 The Netherlands — #23'
  'type': 'vless'
  'server': '95.163.232.171'
  'port': !!int '14443'
  'uuid': 'fb67fd37-8d41-43a9-a093-c0b807fc5299'
  'network': 'ws'
  'udp': !!bool 'true'
- 'name': '🇳🇱 The Netherlands — #28'
  'type': 'vless'
  'server': '188.225.75.183'
  'port': !!int '12443'
  'uuid': 'a95b3155-bc03-4789-b367-944b83be8f86'
  'network': 'raw'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'api-maps.yandex.ru'
  'reality-opts':
    'public-key': 'Nq6KRzyjC95-W9JtG13EwPzNccKnZwMzhxEM_3zkdk8'
    'short-id': '41a2b7c9'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'firefox'
- 'name': '🇳🇱 The Netherlands — #30'
  'type': 'vless'
  'server': '85.198.70.200'
  'port': !!int '14406'
  'uuid': '237f91bf-102e-4077-8cc3-baebccb42936'
  'network': 'raw'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'vk.ru'
  'reality-opts':
    'public-key': 'ldAmsl3dqTCUBmlmA8CS9ZnpznP6cFWj9AxNddWnbxY'
    'short-id': '1a2b3c4d5e6f7a8b'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'firefox'
- 'name': '🇳🇱 The Netherlands — #31'
  'type': 'vless'
  'server': '85.198.70.200'
  'port': !!int '14406'
  'uuid': '237f91bf-102e-4077-8cc3-baebccb42936'
  'network': 'raw'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'vk.ru'
  'reality-opts':
    'public-key': 'ldAmsl3dqTCUBmlmA8CS9ZnpznP6cFWj9AxNddWnbxY'
    'short-id': '1a2b3c4d5e6f7a8b'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'chrome'
- 'name': '🇳🇱 The Netherlands — #32'
  'type': 'vless'
  'server': '31.131.255.35'
  'port': !!int '9894'
  'uuid': '5d16ac22-6eea-426f-b778-6f4c2961faef'
  'network': 'grpc'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'dl.google.com'
  'reality-opts':
    'public-key': 'sm3E3hjmT6_Gmg_O9rBz4nfXYrHpnl6-LvcCp6T6_xc'
    'short-id': 'aa'
  'client-fingerprint': 'safari'
- 'name': '🇳🇱 The Netherlands — #33'
  'type': 'vless'
  'server': '185.65.148.217'
  'port': !!int '15443'
  'uuid': '3f63c86c-ac4a-4900-85cf-4fedf93c2ca5'
  'network': 'raw'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'rutube.ru'
  'reality-opts':
    'public-key': '10rVZPoOUP1TlQviIAsQ_jAROX0fRQxH0C92nq_zGQc'
    'short-id': '43dcff53849b81e6'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'chrome'
- 'name': '🇳🇱 The Netherlands — #34'
  'type': 'vless'
  'server': '185.65.148.217'
  'port': !!int '15443'
  'uuid': '3f63c86c-ac4a-4900-85cf-4fedf93c2ca5'
  'network': 'raw'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'rutube.ru'
  'reality-opts':
    'public-key': '10rVZPoOUP1TlQviIAsQ_jAROX0fRQxH0C92nq_zGQc'
    'short-id': '43dcff53849b81e6'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'edge'
- 'name': '🇳🇱 The Netherlands — #35'
  'type': 'vless'
  'server': '185.65.148.217'
  'port': !!int '15443'
  'uuid': '3f63c86c-ac4a-4900-85cf-4fedf93c2ca5'
  'network': 'raw'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'rutube.ru'
  'reality-opts':
    'public-key': '10rVZPoOUP1TlQviIAsQ_jAROX0fRQxH0C92nq_zGQc'
    'short-id': '43dcff53849b81e6'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'firefox'
- 'name': '🇳🇱 The Netherlands — #36'
  'type': 'vless'
  'server': '185.65.148.217'
  'port': !!int '15443'
  'uuid': '3f63c86c-ac4a-4900-85cf-4fedf93c2ca5'
  'network': 'raw'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'rutube.ru'
  'reality-opts':
    'public-key': '10rVZPoOUP1TlQviIAsQ_jAROX0fRQxH0C92nq_zGQc'
    'short-id': '43dcff53849b81e6'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'qq'
- 'name': '🇳🇱 The Netherlands — #37'
  'type': 'vless'
  'server': '185.65.148.217'
  'port': !!int '15443'
  'uuid': '3f63c86c-ac4a-4900-85cf-4fedf93c2ca5'
  'network': 'raw'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'rutube.ru'
  'reality-opts':
    'public-key': '10rVZPoOUP1TlQviIAsQ_jAROX0fRQxH0C92nq_zGQc'
    'short-id': '43dcff53849b81e6'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'safari'
'proxy-groups':
- 'name': 'PROXY'
  'type': 'select'
  'proxies':
  - '🚀 Авто'
  - '📺 YouTube'
  - '🎮 League'
  - '🇩🇪 Frankfurt'
  - '🇵🇱 Polska'
  - '🇪🇪 Eesti'
  - '🇭🇺 Hungary'
  - '⚡ Российские'
  - '⚠️ Lite-версия подписки устарела'
  - 'Обновите ссылку на актуальную'
  - 'https://github.com/zieng2/wl'
  - 'https://t.me/zieng2'
  - '🇷🇺 Beget — #1'
  - '🇷🇺 Beget — #2'
  - '🇷🇺 Beget — #3'
  - '🇷🇺 Beget — #4'
  - '🇷🇺 MegaMax Network — #5'
  - '🇦🇹 Austria — #6'
  - '🇦🇹 Austria — #7'
  - '🇦🇹 Austria — #8'
  - '🇦🇹 Austria — #9'
  - '🇦🇹 Austria — #10'
  - '🇦🇹 Austria — #11'
  - '🇨🇭 Switzerland — #12'
  - '🇨🇿 Czechia — #13'
  - '🇨🇿 Czechia — #14'
  - '🇨🇿 Czechia — #15'
  - '🇩🇪 Germany — #16'
  - '🇩🇪 Germany — #17'
  - '🇳🇱 The Netherlands — #19'
  - '🇳🇱 The Netherlands — #23'
  - '🇳🇱 The Netherlands — #28'
  - '🇳🇱 The Netherlands — #30'
  - '🇳🇱 The Netherlands — #31'
  - '🇳🇱 The Netherlands — #32'
  - '🇳🇱 The Netherlands — #33'
  - '🇳🇱 The Netherlands — #34'
  - '🇳🇱 The Netherlands — #35'
- 'name': '🚀 Авто'
  'type': 'url-test'
  'proxies':
  - '⚠️ Lite-версия подписки устарела'
  - 'Обновите ссылку на актуальную'
  - 'https://github.com/zieng2/wl'
  - 'https://t.me/zieng2'
  - '🇷🇺 Beget — #1'
  - '🇷🇺 Beget — #2'
  - '🇷🇺 Beget — #3'
  - '🇷🇺 Beget — #4'
  - '🇷🇺 MegaMax Network — #5'
  - '🇦🇹 Austria — #6'
  - '🇦🇹 Austria — #7'
  - '🇦🇹 Austria — #8'
  - '🇦🇹 Austria — #9'
  - '🇦🇹 Austria — #10'
  - '🇦🇹 Austria — #11'
  - '🇨🇭 Switzerland — #12'
  - '🇨🇿 Czechia — #13'
  - '🇨🇿 Czechia — #14'
  - '🇨🇿 Czechia — #15'
  - '🇩🇪 Germany — #16'
  - '🇩🇪 Germany — #17'
  - '🇳🇱 The Netherlands — #19'
  - '🇳🇱 The Netherlands — #23'
  - '🇳🇱 The Netherlands — #28'
  - '🇳🇱 The Netherlands — #30'
  - '🇳🇱 The Netherlands — #31'
  - '🇳🇱 The Netherlands — #32'
  - '🇳🇱 The Netherlands — #33'
  - '🇳🇱 The Netherlands — #34'
  - '🇳🇱 The Netherlands — #35'
  - '🇳🇱 The Netherlands — #36'
  - '🇳🇱 The Netherlands — #37'
  'url': 'https://www.google.com/generate_204'
  'interval': !!int '60'
  'tolerance': !!int '100'
- 'name': '📺 YouTube'
  'type': 'url-test'
  'proxies':
  - '⚠️ Lite-версия подписки устарела'
  - 'Обновите ссылку на актуальную'
  - 'https://github.com/zieng2/wl'
  - 'https://t.me/zieng2'
  - '🇦🇹 Austria — #6'
  - '🇦🇹 Austria — #7'
  - '🇦🇹 Austria — #8'
  - '🇦🇹 Austria — #9'
  - '🇦🇹 Austria — #10'
  - '🇦🇹 Austria — #11'
  - '🇨🇭 Switzerland — #12'
  - '🇨🇿 Czechia — #13'
  - '🇨🇿 Czechia — #14'
  - '🇨🇿 Czechia — #15'
  - '🇩🇪 Germany — #16'
  - '🇩🇪 Germany — #17'
  - '🇳🇱 The Netherlands — #19'
  - '🇳🇱 The Netherlands — #23'
  - '🇳🇱 The Netherlands — #28'
  - '🇳🇱 The Netherlands — #30'
  - '🇳🇱 The Netherlands — #31'
  - '🇳🇱 The Netherlands — #32'
  - '🇳🇱 The Netherlands — #33'
  - '🇳🇱 The Netherlands — #34'
  - '🇳🇱 The Netherlands — #35'
  - '🇳🇱 The Netherlands — #36'
  - '🇳🇱 The Netherlands — #37'
  'url': 'https://www.youtube.com/generate_204'
  'interval': !!int '120'
  'tolerance': !!int '150'
- 'name': '🎮 League'
  'type': 'url-test'
  'proxies': &id001
  - '🇷🇺 Beget — #1'
  - '🇷🇺 Beget — #2'
  - '🇷🇺 Beget — #3'
  - '🇷🇺 Beget — #4'
  - '🇷🇺 MegaMax Network — #5'
  'url': 'https://www.google.com/generate_204'
  'interval': !!int '60'
  'tolerance': !!int '30'
- 'name': '🇩🇪 Frankfurt'
  'type': 'url-test'
  'proxies':
  - '🇩🇪 Germany — #16'
  - '🇩🇪 Germany — #17'
  'url': 'https://cloudflare.com/cdn-cgi/trace'
  'interval': !!int '60'
  'tolerance': !!int '50'
- 'name': '🇵🇱 Polska'
  'type': 'url-test'
  'proxies':
  - '⚠️ Lite-версия подписки устарела'
  - 'Обновите ссылку на актуальную'
  - 'https://github.com/zieng2/wl'
  - 'https://t.me/zieng2'
  - '🇦🇹 Austria — #6'
  - '🇦🇹 Austria — #7'
  - '🇦🇹 Austria — #8'
  - '🇦🇹 Austria — #9'
  - '🇦🇹 Austria — #10'
  - '🇦🇹 Austria — #11'
  - '🇨🇭 Switzerland — #12'
  - '🇨🇿 Czechia — #13'
  - '🇨🇿 Czechia — #14'
  - '🇨🇿 Czechia — #15'
  - '🇩🇪 Germany — #16'
  - '🇩🇪 Germany — #17'
  - '🇳🇱 The Netherlands — #19'
  - '🇳🇱 The Netherlands — #23'
  - '🇳🇱 The Netherlands — #28'
  - '🇳🇱 The Netherlands — #30'
  - '🇳🇱 The Netherlands — #31'
  - '🇳🇱 The Netherlands — #32'
  - '🇳🇱 The Netherlands — #33'
  - '🇳🇱 The Netherlands — #34'
  - '🇳🇱 The Netherlands — #35'
  - '🇳🇱 The Netherlands — #36'
  - '🇳🇱 The Netherlands — #37'
  'url': 'https://cloudflare.com/cdn-cgi/trace'
  'interval': !!int '60'
  'tolerance': !!int '50'
- 'name': '🇪🇪 Eesti'
  'type': 'url-test'
  'proxies':
  - '⚠️ Lite-версия подписки устарела'
  - 'Обновите ссылку на актуальную'
  - 'https://github.com/zieng2/wl'
  - 'https://t.me/zieng2'
  - '🇦🇹 Austria — #6'
  - '🇦🇹 Austria — #7'
  - '🇦🇹 Austria — #8'
  - '🇦🇹 Austria — #9'
  - '🇦🇹 Austria — #10'
  - '🇦🇹 Austria — #11'
  - '🇨🇭 Switzerland — #12'
  - '🇨🇿 Czechia — #13'
  - '🇨🇿 Czechia — #14'
  - '🇨🇿 Czechia — #15'
  - '🇩🇪 Germany — #16'
  - '🇩🇪 Germany — #17'
  - '🇳🇱 The Netherlands — #19'
  - '🇳🇱 The Netherlands — #23'
  - '🇳🇱 The Netherlands — #28'
  - '🇳🇱 The Netherlands — #30'
  - '🇳🇱 The Netherlands — #31'
  - '🇳🇱 The Netherlands — #32'
  - '🇳🇱 The Netherlands — #33'
  - '🇳🇱 The Netherlands — #34'
  - '🇳🇱 The Netherlands — #35'
  - '🇳🇱 The Netherlands — #36'
  - '🇳🇱 The Netherlands — #37'
  'url': 'https://cloudflare.com/cdn-cgi/trace'
  'interval': !!int '60'
  'tolerance': !!int '50'
- 'name': '🇭🇺 Hungary'
  'type': 'url-test'
  'proxies':
  - '⚠️ Lite-версия подписки устарела'
  - 'Обновите ссылку на актуальную'
  - 'https://github.com/zieng2/wl'
  - 'https://t.me/zieng2'
  - '🇦🇹 Austria — #6'
  - '🇦🇹 Austria — #7'
  - '🇦🇹 Austria — #8'
  - '🇦🇹 Austria — #9'
  - '🇦🇹 Austria — #10'
  - '🇦🇹 Austria — #11'
  - '🇨🇭 Switzerland — #12'
  - '🇨🇿 Czechia — #13'
  - '🇨🇿 Czechia — #14'
  - '🇨🇿 Czechia — #15'
  - '🇩🇪 Germany — #16'
  - '🇩🇪 Germany — #17'
  - '🇳🇱 The Netherlands — #19'
  - '🇳🇱 The Netherlands — #23'
  - '🇳🇱 The Netherlands — #28'
  - '🇳🇱 The Netherlands — #30'
  - '🇳🇱 The Netherlands — #31'
  - '🇳🇱 The Netherlands — #32'
  - '🇳🇱 The Netherlands — #33'
  - '🇳🇱 The Netherlands — #34'
  - '🇳🇱 The Netherlands — #35'
  - '🇳🇱 The Netherlands — #36'
  - '🇳🇱 The Netherlands — #37'
  'url': 'https://cloudflare.com/cdn-cgi/trace'
  'interval': !!int '60'
  'tolerance': !!int '50'
- 'name': '⚡ Российские'
  'type': 'url-test'
  'proxies': *id001
  'url': 'https://yandex.ru/internet'
  'interval': !!int '60'
  'tolerance': !!int '30'
'rules':
- 'DOMAIN-SUFFIX,youtube.com,📺 YouTube'
- 'DOMAIN-SUFFIX,googlevideo.com,📺 YouTube'
- 'DOMAIN-SUFFIX,ytimg.com,📺 YouTube'
- 'DOMAIN-SUFFIX,ggpht.com,📺 YouTube'
- 'DOMAIN-SUFFIX,youtu.be,📺 YouTube'
- 'DOMAIN,youtube.googleapis.com,📺 YouTube'
- 'DOMAIN-SUFFIX,twitch.tv,📺 YouTube'
- 'DOMAIN-SUFFIX,netflix.com,📺 YouTube'
- 'DOMAIN-SUFFIX,hulu.com,📺 YouTube'
- 'MATCH,PROXY'
